"""Seed data for the CRANE Second Brain vault (papers, repos).

Facts here come from live lookups on 2026-10-02:
  * papers  — Hugging Face papers search (titles, dates, upvotes, abstract summaries)
  * repos   — GitHub API (stars, license, last push)
  * 'fit' judgements reference the team's own Sep-2026 research (knowledge/research/*)
"""

# (arxiv_id, short_name, full_title, published, hf_upvotes, what_it_is, [concepts], group, fit_for_berylize)
PAPERS = [
 ("2512.04677", "Live Avatar", "Live Avatar: Streaming Real-time Audio-Driven Avatar Generation with Infinite Length", "2025-12", 133,
  "14B diffusion model for real-time, infinite-length audio-driven avatars. Timestep-forcing Pipeline Parallelism and a Rolling Sink Frame Mechanism keep identity stable over long streams.",
  ["Autoregressive Streaming Diffusion", "Long-Horizon Memory", "Block-wise Generation", "Cost Ceiling and GPU Session Economics"], "Streaming core",
  "Best published reference for infinite-length streaming. Team research ruled it out as the base: needs ~5x H800 for real-time, far over the ~$0.40/hr ceiling. Study its rolling sink frame for identity stability."),
 ("2601.00664", "Avatar Forcing", "Avatar Forcing: Real-Time Interactive Head Avatar Generation for Natural Conversation", "2026-01", 58,
  "Real-time interactive head avatar using diffusion forcing, with label-free preference optimization for expressive motion at low latency.",
  ["Turn-Taking and Full-Duplex", "Listening Behavior", "Emotion and Expression Control", "Exposure Bias and Identity Drift"], "Bi-directional conversation",
  "Directly targets the 'feels like a conversation' goal: reactive, expressive head motion with low latency. Preference optimization is a route to tune away uncanny motion without labels."),
 ("2512.23379", "SoulX-FlashTalk", "SoulX-FlashTalk: Real-Time Infinite Streaming of Audio-Driven Avatars via Self-Correcting Bidirectional Distillation", "2025-12", 3,
  "14B system for high-fidelity real-time audio-driven avatars: bidirectional attention, error-correction, hardware-accelerated inference.",
  ["Distillation and Quantization", "Exposure Bias and Identity Drift", "Cold Start Strategy"], "Streaming core",
  "Sibling of the FlashHead family the team chose as foundation. 14B tier is the quality ceiling; the 1.3B FlashHead is the affordable tier."),
 ("2603.14331", "AvatarForcing One-Step", "AvatarForcing: One-Step Streaming Talking Avatars via Local-Future Sliding-Window Denoising", "2026-03", 14,
  "One-step streaming avatars. Attacks exposure bias (errors that accumulate and become irreversible in AR forcing) with local-future sliding-window denoising.",
  ["Exposure Bias and Identity Drift", "Autoregressive Streaming Diffusion", "Distillation and Quantization"], "Streaming core",
  "One denoising step is what makes cheap GPUs viable. Read for the exposure-bias fix, which is the main failure mode of long calls."),
 ("2412.04037", "INFP", "INFP: Audio-Driven Interactive Head Generation in Dyadic Conversations", "2024-12", 0,
  "Audio-driven head generation for dyadic conversation: the agent alternates between speaking and listening driven by both parties' audio.",
  ["Turn-Taking and Full-Duplex", "Listening Behavior"], "Bi-directional conversation",
  "Foundational paper for the idea that listening is generated from the user's audio, not idled. Pairs with a semantic VAD for state."),
 ("2512.09327", "UniLS", "UniLS: End-to-End Audio-Driven Avatars for Unified Listening and Speaking", "2025-12", 0,
  "Unified speak-listen facial expression from dual-track audio; two-stage training learns internal motion priors to solve listener-motion generation.",
  ["Listening Behavior", "Turn-Taking and Full-Duplex", "Audio-Driven Motion Latents"], "Bi-directional conversation",
  "Listening is the rarest shipped property in open work (see team research). UniLS is the cleanest recipe for one model that speaks and listens."),
 ("2603.17427", "ECHO", "ECHO: Towards Emotionally Appropriate and Contextually Aware Interactive Head Generation", "2026-03", 0,
  "Interactive head generation with long-range conversational context and spatially aware decoupled cross-attention modulation.",
  ["Listening Behavior", "Emotion and Expression Control", "Conversation Brain and RAG"], "Bi-directional conversation",
  "Expression conditioned on what was said, not just how it sounded. The hook where the LLM can steer emotion."),
 ("2609.35616", "EvolvingAvatar", "EvolvingAvatar: Interactive 3D Head Generation That Adapts as Conversations Unfold", "2026-09", 3,
  "Interactive 3D head generator whose parameters adapt during the conversation, coordinating speaking and listening motion.",
  ["Listening Behavior", "Emotion and Expression Control", "ARKit Blendshapes"], "Bi-directional conversation",
  "Very recent. Online adaptation is how an avatar avoids repeating the same canned reactions across a long conversation."),
 ("2412.01064", "FLOAT", "FLOAT: Generative Motion Latent Flow Matching for Audio-driven Talking Portrait", "2024-12", 47,
  "Flow matching in a learned motion latent space with a transformer vector-field predictor; temporally consistent and emotion-enhanced talking portraits.",
  ["Audio-Driven Motion Latents", "Emotion and Expression Control"], "Expression and realism",
  "Motion-latent flow matching is faster than pixel-space diffusion and exposes an emotion control. A strong cheap-GPU design pattern."),
 ("2501.10687", "EMO2", "EMO2: End-Effector Guided Audio-Driven Avatar Video Generation", "2025-01", 15,
  "Generates expressive facial expression and hand gestures: audio-to-hand-pose first, then a diffusion model synthesizes the video.",
  ["Emotion and Expression Control", "Audio-Driven Motion Latents"], "Expression and realism",
  "Gestures are a big part of 'alive'. The two-stage trick (pose first, render second) is reusable."),
 ("2412.04448", "MEMO", "MEMO: Memory-Guided Diffusion for Expressive Talking Video Generation", "2024-12", 9,
  "Memory-guided emotion-aware diffusion: lip sync, long-term identity consistency, expression aligned to audio emotion.",
  ["Long-Horizon Memory", "Emotion and Expression Control", "Exposure Bias and Identity Drift"], "Expression and realism",
  "Memory for identity consistency is the same problem as rolling sink frames. Emotion-aware part maps to the expression layer."),
 ("2508.02944", "X-Actor", "X-Actor: Emotional and Expressive Long-Range Portrait Acting from Audio", "2025-08", 0,
  "Two-stage: audio-conditioned autoregressive diffusion for long-range expressive motion, then a diffusion video synthesis module.",
  ["Emotion and Expression Control", "Autoregressive Streaming Diffusion"], "Expression and realism",
  "Acting-quality emotion across long spans, not frame-by-frame lip flap. Informs the emotion arc layer above the renderer."),
 ("2506.05806", "LLIA", "LLIA: Enabling Low-Latency Interactive Avatars: Real-Time Audio-Driven Portrait Video Generation with Diffusion Models", "2025-06", 2,
  "Diffusion-based audio-driven portrait video at real-time speed and low latency aimed at interactive virtual humans.",
  ["Latency Budget", "Autoregressive Streaming Diffusion"], "Real-time and affordable",
  "Explicit latency framing. Use its numbers as a comparison point when profiling first-frame time."),
 ("2508.05115", "RAP", "RAP: Real-time Audio-driven Portrait Animation with Video Diffusion Transformer", "2025-08", 4,
  "Real-time audio-driven portrait animation on a video DiT: hybrid attention for audio control and fidelity, static-dynamic training-inference paradigm.",
  ["Latency Budget", "Distillation and Quantization", "Autoregressive Streaming Diffusion"], "Real-time and affordable",
  "Shows how to keep DiT quality while hitting real-time. Hybrid attention is a drop-in idea for audio conditioning."),
 ("2411.19509", "Ditto", "Ditto: Motion-Space Diffusion for Controllable Realtime Talking Head Synthesis", "2024-11", 3,
  "Diffusion over an explicit motion space with an optimized inference pipeline (audio features, motion generation, rendering) for controllable real-time synthesis.",
  ["Audio-Driven Motion Latents", "Latency Budget", "Emotion and Expression Control"], "Real-time and affordable",
  "Apache-2.0 code exists (see Ditto repo note). Explicit motion space gives controllability for expression and head pose."),
 ("2506.22065", "MirrorMe", "MirrorMe: Towards Realtime and High Fidelity Audio-Driven Halfbody Animation", "2025-06", 0,
  "Real-time audio-driven half-body animation with a diffusion transformer; identity consistency, audio sync, progressive training.",
  ["Latency Budget", "Long-Horizon Memory", "Emotion and Expression Control"], "Real-time and affordable",
  "Half-body (shoulders and torso movement) removes the 'floating head' tell that triggers uncanny valley."),
 ("2512.11423", "JoyAvatar", "JoyAvatar: Real-time and Infinite Audio-Driven Avatar Generation with Autoregressive Diffusion", "2025-12", 1,
  "Real-time infinite audio-driven avatar via progressive step bootstrapping, motion condition injection, unbounded rotary positional encoding.",
  ["Autoregressive Streaming Diffusion", "Long-Horizon Memory", "Distillation and Quantization"], "Streaming core",
  "Unbounded RoPE solves the 'positions run out on long streams' problem. Relevant if building or fine-tuning an AR video model."),
 ("2603.11746", "SoulX-LiveAct", "SoulX-LiveAct: Towards Hour-Scale Real-Time Human Animation with Neighbor Forcing and ConvKV Memory", "2026-03", 0,
  "Hour-scale real-time human animation: Neighbor Forcing and structured ConvKV memory make autoregressive diffusion scale.",
  ["Long-Horizon Memory", "Autoregressive Streaming Diffusion", "Exposure Bias and Identity Drift"], "Streaming core",
  "Hour-scale matters for a product (support calls, tutors). ConvKV memory is the KV-cache design to know."),
 ("2608.13602", "Omni-LiveAvatar", "Omni-LiveAvatar: Minute-Level Real-Time Streaming Joint Audio-Video Avatar Generation", "2026-08", 0,
  "Joint audio-video avatar generation in real time for minutes at a time via progressive autoregressive distillation and rolling prompt planning.",
  ["Autoregressive Streaming Diffusion", "Distillation and Quantization", "Licensing Audit"], "Streaming core",
  "Team research (Sep 2026): README says code and checkpoints are not released. Track it, do not plan around it."),
 ("2604.23632", "Hallo-Live", "Hallo-Live: Real-Time Streaming Joint Audio-Video Avatar Generation with Asynchronous Dual-Stream and Human-Centric Preference Distillation", "2026-04", 1,
  "Streaming dual-stream diffusion for text-driven joint audio-video avatars with preference-guided distillation.",
  ["Distillation and Quantization", "Autoregressive Streaming Diffusion", "Cost Ceiling and GPU Session Economics"], "Streaming core",
  "MIT licensed but team research measured 2x H200 for ~20 FPS: reference architecture only. Preference distillation is the transferable idea."),
 ("2511.12662", "Hi-Reco", "Hi-Reco: High-Fidelity Real-Time Conversational Digital Humans", "2025-11", 0,
  "Conversational digital human system: retrieval-augmented dialogue generation, history augmentation, intent-based routing.",
  ["Conversation Brain and RAG", "Latency Budget"], "Conversation brain and speech",
  "The brain side of the loop. RAG plus intent routing is the pattern this very vault implements for Berylize."),
 ("2410.17799", "OmniFlatten", "OmniFlatten: An End-to-end GPT Model for Seamless Voice Conversation", "2024-10", 18,
  "Full-duplex spoken dialogue GPT: multi-stage post-training that fuses speech and text without changing the base architecture.",
  ["Turn-Taking and Full-Duplex", "Barge-In"], "Conversation brain and speech",
  "Shows full-duplex can be post-trained onto an LLM. Context for the Duplug-style turn-taking model in the pipeline."),
 ("2503.04721", "Full-Duplex-Bench", "Full-Duplex-Bench: A Benchmark to Evaluate Full-duplex Spoken Dialogue Models on Turn-taking Capabilities", "2025-03", 4,
  "Benchmark for pause handling, backchanneling, turn-taking, and interruption management.",
  ["Turn-Taking and Full-Duplex", "Barge-In", "Verification Layer"], "Conversation brain and speech",
  "Gives measurable test cases for barge-in and backchannel. Use as the acceptance test list for the conversation layer."),
 ("2509.06502", "FireRedChat", "FireRedChat: A Pluggable, Full-Duplex Voice Interaction System with Cascaded and Semi-Cascaded Implementations", "2025-09", 0,
  "Modular full-duplex voice system: turn-taking controller, interaction module, dialogue manager; cascaded and semi-cascaded variants.",
  ["Turn-Taking and Full-Duplex", "Barge-In", "Streaming ASR and Semantic VAD", "Streaming TTS"], "Conversation brain and speech",
  "A pluggable architecture that maps almost 1:1 onto Beryl's Duplug + brain + TTS nodes."),
 ("2503.17032", "TaoAvatar", "TaoAvatar: Real-Time Lifelike Full-Body Talking Avatars for Augmented Reality via 3D Gaussian Splatting", "2025-03", 27,
  "Lightweight 3DGS full-body talking avatar running in real time across devices; distillation for non-rigid deformation.",
  ["Gaussian Splatting Avatars", "Cost Ceiling and GPU Session Economics", "ARKit Blendshapes"], "Real-time and affordable",
  "The cheap alternative: render on the viewer's device, so server GPU cost goes to near zero. Needs a rigged capture, unlike photo-in pipelines."),
]

# (note_title, owner/repo, stars, license, pushed, kind, one_liner, fit, rank)
REPOS = [
 ("SoulX-FlashHead", "Soul-AILab/SoulX-FlashHead", 1097, "Apache-2.0", "2026-05-28", "Render core (foundation)",
  "Unified 1.3B-parameter framework for high-fidelity, infinite-length talking head generation.",
  "Team's chosen foundation (research Part 1): Apache-2.0 with clean dependency tree, ~1x RTX 4090 real-time per README. Best fit for the $0.40/hr ceiling.", 1),
 ("SoulX-FlashTalk", "Soul-AILab/SoulX-FlashTalk", 1529, "Apache-2.0", "2026-07-30", "Render core (quality tier)",
  "14B model with sub-second start-up latency (0.87s per repo description), real-time infinite streaming.",
  "Quality-ceiling sibling of FlashHead. Use when budget allows a bigger GPU or for batch/offline mastering.", 2),
 ("OpenAvatarChat", "HumanAIGC-Engineering/OpenAvatarChat", 3785, "Apache-2.0", "2026-07-31", "Full conversational stack",
  "Modular interactive avatar chat with replaceable ASR, LLM, TTS and avatar backends.",
  "Closest open reference to the whole loop (mic to face). Read its handler/backend plug-in layout before designing Beryl's node contracts.", 3),
 ("Pipecat", "pipecat-ai/pipecat", 16150, "BSD-2-Clause", "2026-10-03", "Realtime voice-agent framework",
  "Open source framework for voice agents, multimodal apps and realtime AI.",
  "Pipeline/frame abstractions for streaming audio, VAD, interruption handling. Candidate orchestration layer for the audio side.", 4),
 ("LiveKit Agents", "livekit/agents", 14453, "Apache-2.0", "2026-10-03", "WebRTC agent framework",
  "Framework for building realtime voice AI agents (audio, video) on LiveKit.",
  "Production WebRTC transport, turn detection and agent lifecycle. Solves delivery so effort goes to the avatar itself.", 5),
 ("LiveAvatar", "Alibaba-Quark/LiveAvatar", 2448, "Apache-2.0", "2026-08-24", "Reference architecture",
  "ECCV 2026 Spotlight: streaming real-time audio-driven avatar generation with infinite length.",
  "Excellent ideas, wrong hardware: team research found 5x H800 80GB for real-time. Adopt concepts (block-wise gen, rolling sink frame), not the deployment.", 6),
 ("MuseTalk", "TMElyralab/MuseTalk", 6653, "NOASSERTION (check LICENSE)", "2025-09-26", "Lip-sync module",
  "Real-time high quality lip synchronization with latent space inpainting.",
  "Practical lip-sync on modest GPUs and a common Linly/OpenAvatar backend. License field is not machine-readable: audit before commercial use.", 7),
 ("Ditto", "antgroup/ditto-talkinghead", 899, "Apache-2.0", "2025-11-12", "Real-time talking head",
  "ACM MM 2025: motion-space diffusion for controllable real-time talking head synthesis.",
  "Apache-2.0 real-time option with explicit motion control. Good candidate for the bake-off against FlashHead on a single GPU.", 8),
 ("InfiniteTalk", "MeiGen-AI/InfiniteTalk", 7956, "Apache-2.0", "2026-05-22", "Long-form talking video",
  "Unlimited-length talking video generation supporting image-to-video and video-to-video.",
  "Strong community traction for long clips. Check streaming latency before using for live; likely better for offline Berylize Creatives output.", 9),
 ("Linly-Talker", "Kedreamix/Linly-Talker", 3455, "MIT", "2026-02-10", "Conversational WebUI",
  "Digital avatar conversational system combining LLM, ASR, TTS, voice cloning and several talking-head backends.",
  "MIT-licensed integration example showing how to hot-swap backends. Useful for the Node Inspector 'one-click model swap' design.", 10),
]

HONORABLE = [
 ("Duix-Avatar", "duixcom/Duix-Avatar", 15639, "NOASSERTION", "Offline avatar and voice-clone toolkit; most-starred in the topic but non-standard license, so audit first."),
 ("LiteAvatar", "HumanAIGC/lite-avatar", 482, "MIT", "CPU-only real-time 2D audio-to-face avatar; backend for OpenAvatarChat. The floor of the cost curve."),
 ("EchoMimic", "antgroup/echomimic", 4307, "Apache-2.0", "Editable-landmark audio-driven portrait animation (AAAI 2025)."),
 ("LatentSync", "bytedance/LatentSync", 6105, "Apache-2.0", "Stable-Diffusion based lip sync, strong quality but heavier."),
 ("Hallo3", "fudan-generative-vision/hallo3", 1406, "MIT", "Dynamic, realistic portrait animation with video diffusion transformers."),
]
